// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5RCRnDljtmplYj_VQVqekUggnraeb3Bc',
    appId: '1:976666084314:android:a5072d27a965df29ca36e3',
    messagingSenderId: '976666084314',
    projectId: 'appgym-7f699',
    storageBucket: 'appgym-7f699.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAvYDibQHsZPEkdlJXSVVIQJH7fJEIUqQ',
    appId: '1:976666084314:ios:a9e767b90c9cb606ca36e3',
    messagingSenderId: '976666084314',
    projectId: 'appgym-7f699',
    storageBucket: 'appgym-7f699.firebasestorage.app',
    iosBundleId: 'com.example.tccTreinoIa',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_YeMWrisxcOB5fAuD8yZ2XZQyAGFuB0',
    appId: '1:976666084314:web:7ac4a2694206c147ca36e3',
    messagingSenderId: '976666084314',
    projectId: 'appgym-7f699',
    authDomain: 'appgym-7f699.firebaseapp.com',
    storageBucket: 'appgym-7f699.firebasestorage.app',
  );

}